module.exports = [
  { city: 'Astana',    handle: 'astana.hub' },
  { city: 'Kyzylorda',    handle: 'kyzylordahub' },
  { city: 'Zhambyl',    handle: 'zhambyl_hub' },
  { city: 'Almaty',    handle: 'almaty_hub' },
  { city: 'Atyrau',    handle: 'atyrau_it_hub' },
  { city: 'Pavlodar',    handle: 'pavlodar.hub' },
  { city: 'Uralsk',    handle: 'batys.hub' },
  { city: 'Oskemen',    handle: 'oskemen.hub' },
  { city: 'Jetisu',    handle: 'jetisu_digital' },
  { city: 'Shymkent',    handle: 'shymkent__hub' },
  { city: 'Alatau',    handle: 'alatau.hub' },
  { city: 'Mangystau',    handle: 'mangystau.hub' },
  { city: 'Turkistan',    handle: 'turkistan.hub' },
  { city: 'Ulytau',    handle: 'ulytau.hub' },
  { city: 'Aqtobe',    handle: 'aqtobe.hub' },
  { city: 'Aqmola',    handle: 'aqmola.hub' },
  { city: 'Petropavl',    handle: 'sko_hub' },
];